backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://elite-door.com
logo_url: https://elite-dorr.com/favicon.svg
media_folder: src/assets/images/managed # Location where files will be stored in the repo
public_folder: src/assets/images/managed # The src attribute for uploaded media
collections:
  - name: home-page
    identifier_field: name
    label: Home Page
    files:
      - name: banner
        label: Banner
        file: src/content/home-page/banner.json
        fields:
          - name: slogan
            label: Slogan
            description: Write a slogan...
            widget: markdown
          - name: image
            label: Image
            description: ...or use an image
            widget: image
            required: false
      - name: about
        label: About
        file: src/content/home-page/about.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: description
            label: Description
            widget: markdown
          - name: location_card
            label: Location Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
          - name: business_card
            label: Business Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
          - name: service_card
            label: Service Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
