backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://elite-door.com/
display_url: https://elite-door.com/
logo_url: https://elite-door.com/logo-large.svg
media_folder: src/assets/images/managed # Location where files will be stored in the repo
public_folder: src/assets/images/managed # The src attribute for uploaded media
collections:
  - name: home-page
    identifier_field: name
    label: Home Page
    files:
      - name: banner
        label: Banner
        file: src/content/home-page/banner.json
        fields:
          - name: slogan
            label: Slogan
            hint: Write a slogan...
            widget: markdown
            editor_components:
              - code-block
          - name: image
            label: Image
            hint: ...or use an image
            widget: list
            summary: "{{fields.alt}}"
            required: false
            max: 1
            fields:
              - name: src
                label: Source
                widget: image
              - name: alt
                label: Description
                hint: For accessibility or if the image doesn't load
                widget: string
      - name: about-us
        label: About Us
        file: src/content/home-page/about-us.json
        fields:
          - name: image
            label: Image
            widget: list
            summary: "{{fields.alt}}"
            required: false
            max: 1
            fields:
              - name: src
                label: Source
                widget: image
              - name: alt
                label: Description
                hint: For accessibility or if the image doesn't load
                widget: string
          - name: description
            label: Description
            widget: markdown
            editor_components:
              - code-block
          - name: locationCard
            label: Location Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
          - name: businessCard
            label: Business Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
          - name: serviceCard
            label: Service Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
      - name: our-work
        label: Our Work
        file: src/content/home-page/our-work.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: galleries
            label: Galleries
            label_singular: Gallery
            widget: list
            summary: "{{fields.name}}"
            fields:
              - name: name
                label: Name
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
                required: false
              - name: subDescriptions
                label: Sub-descriptions
                label_singular: Sub-description
                widget: list
                fields:
                  - name: description
                    label: Description
                    widget: markdown
                    editor_components:
                      - code-block
              - name: images
                label: Images
                label_singular: Image
                widget: "list"
                summary: "{{fields.alt}}"
                fields:
                  - name: src
                    label: Source
                    widget: image
                  - name: alt
                    label: Description
                    hint: For accessibility or if the image doesn't load
                    widget: string
      - name: certifications
        label: Certifications
        file: src/content/home-page/certifications.json
        fields:
          - name: description
            label: Description
            widget: markdown
            editor_components:
              - code-block
            required: false
          - name: certificates
            label: Certificates
            label_singular: Certificate
            widget: list
            summary: "{{fields.name}}"
            fields:
              - name: name
                label: Name
                widget: string
              - name: image
                label: Image
                widget: object
                fields:
                  - name: src
                    label: Source
                    widget: image
                  - name: alt
                    label: Description
                    hint: For accessibility or if the image doesn't load
                    widget: string
      - name: distributorships
        label: Distributorships
        file: src/content/home-page/distributorships.json
        fields:
          - name: description
            label: Description
            widget: markdown
            editor_components:
              - code-block
            required: false
          - name: distributors
            label: Distributors
            label_singular: Distributor
            widget: list
            summary: "{{fields.name}}"
            fields:
              - name: name
                label: Name
                required: false
                widget: string
              - name: href
                label: Website
                widget: string
              - name: image
                label: Image
                widget: object
                fields:
                  - name: src
                    label: Source
                    widget: image
                  - name: alt
                    label: Description
                    hint: For accessibility or if the image doesn't load
                    widget: string
      - name: contact-us
        label: Contact Us
        file: src/content/home-page/contact-us.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: emailCard
            label: Email Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
          - name: phoneCard
            label: Phone Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
          - name: mailingCard
            label: Mailing Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
          - name: shippingCard
            label: Shipping Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
                editor_components:
                  - code-block
