backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "src/assets/images" # Location where files will be stored in the repo
public_folder: "src/assets/images" # The src attribute for uploaded media
