backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://elite-door.com
logo_url: https://elite-dorr.com/favicon.svg
media_folder: src/assets/images/managed # Location where files will be stored in the repo
public_folder: src/assets/images/managed # The src attribute for uploaded media
collections:
  - name: home-page
    identifier_field: name
    label: Home Page
    files:
      - name: banner
        label: Banner
        file: src/content/home-page/banner.json
        fields:
          - name: slogan
            label: Slogan
            description: Write a slogan...
            widget: markdown
            default: The **ELITE** choice&#10; for commercial door&#10; installation
          - name: image
            label: Image
            description: ...or use an image
            widget: image
            required: false
      - name: about-us
        label: About Us
        file: src/content/home-page/about-us.json
        fields:
          - name: title
            label: Title
            widget: string
            default: About Us
          - name: description
            label: Description
            widget: markdown
          - name: location-card-title
            label: Location Card Title
            widget: string
          - name: location-card-description
            label: Location Card Description
            widget: markdown
          - name: business-card-title
            label: Business Card Title
            widget: string
          - name: business-card-description
            label: Business Card Description
            widget: markdown
          - name: service-card-title
            label: Service Card Title
            widget: string
          - name: service-card-description
            label: Service Card Description
            widget: markdown
