backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "src/assets/images/managed" # Location where files will be stored in the repo
public_folder: "src/assets/images/managed" # The src attribute for uploaded media
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "About Page"
        name: "about-page"
        file: "src/content/about/page.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Intro, name: intro, widget: markdown }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }
