backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
site_url: https://elite-door.com
logo_url: https://elite-dorr.com/favicon.svg
media_folder: src/assets/images/managed # Location where files will be stored in the repo
public_folder: src/assets/images/managed # The src attribute for uploaded media
collections:
  - name: home-page
    identifier_field: name
    label: Home Page
    files:
      - name: banner
        label: Banner
        file: src/content/home-page/banner.json
        fields:
          - name: slogan
            label: Slogan
            description: Write a slogan...
            widget: markdown
          - name: image
            label: Image
            description: ...or use an image
            widget: object
            required: false
            fields:
              - name: src
                label: Source
                widget: image
              - name: alt
                label: Description
                description: For accessibility or if the image doesn't load
                widget: string
      - name: about-us
        label: About Us
        file: src/content/home-page/about-us.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: image
            label: Image
            widget: object
            fields:
              - name: src
                label: Source
                widget: image
              - name: alt
                label: Description
                description: For accessibility or if the image doesn't load
                widget: string
          - name: description
            label: Description
            widget: markdown
          - name: location_card
            label: Location Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
          - name: business_card
            label: Business Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
          - name: service_card
            label: Service Card
            widget: object
            fields:
              - name: title
                label: Title
                widget: string
              - name: description
                label: Description
                widget: markdown
      - name: our-work
        label: Our Work
        file: src/content/home-page/our-work.json
        fields:
          - name: title
            label: Title
            widget: string
          - name: galleries
            label: Galleries
            widget: list
            field:
              name: gallery
              label: Gallery
              widget: object
              fields:
                - name: name
                  label: Name
                  widget: string
                - name: description
                  label: Description
                  widget: string
                - name: "images"
                  label: "Images"
                  widget: "list"
                  field:
                    name: image
                    label: Image
                    widget: object
                    fields:
                      - name: src
                        label: Source
                        widget: image
                      - name: alt
                        label: Description
                        description: For accessibility or if the image doesn't load
                        widget: string
